if("undefined"===typeof ZDVTools){var ZDVTools={version:20150521,self:null,win:window,enableDebug:!1,enableSafeFramesHack:!1,enableMutations:!1,scriptUrl:"//static.ziffdavis.com/jst/zdvtools.min.js",slowAdThreshold:25E3,onViewable:[],onLoaded:[],roundTiming:function(a){return+(Math.round(a/1E3+"e+3")+"e-3")},timings:{init:{timestamp:(new Date).getTime(),timing:window.performance&&performance.now?+(Math.round(window.performance.now()/1E3+"e+3")+"e-3"):null},DFPinit:{timestamp:null,timing:null}},ads:{},
_observer:null,_options:null,_tickerInterval:null,_UUID:null,_msgs:"",_isIFrame:window==window.top?!1:!0,throttleDown:function(){var a=ZDVTools;a._tickerInterval&&a.win.clearInterval(a._tickerInterval);a._tickerInterval=a.win.setInterval(a._tick,150);a.debug("ZDVTools: Slowing down watchdog")},stop:function(){var a=ZDVTools;a._tickerInterval&&a.win.clearInterval(a._tickerInterval);a._observer&&a._observer.disconnect()},debug:function(a,b){window.console&&(window.ZDVTools||parent.ZDVTools||top.ZDVTools).enableDebug&&
(b||(b="green"),console.log("%c"+a,"color: "+b))},generateUUID:function(){return"xxxxxxxxxxxxxyxxxxxxxxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)})},trackZDBB:function(a,b,d,c){var e=ZDVTools;c&&(b||(b=e.win.document.getElementById(c.iframeId)),d||(d=c.name));d||(d=e.getName(b));c||(c=e.getAd());try{var f=e.win.location.hostname}catch(g){}e.debug("ZDVTools: AD "+a+": "+d+" "+c.size+" "+c[a.toLowerCase()].timing);b=e.win.googletag||null;a=["http://zdbb.net/n/WU2TPsgLEeSUDxIxPSpF6g?agent=zdvtool",
"host="+encodeURIComponent(f||""),"ev="+encodeURIComponent(a||""),"li="+encodeURIComponent(c.lineItemId||""),"cid="+encodeURIComponent(c.creativeId||""),"slot="+encodeURIComponent(c.adUnitPath||""),"size="+encodeURIComponent(c.size),"name="+encodeURIComponent(d),"corrid="+encodeURIComponent(c.correlatorId||b?b.pubads().getCorrelator()||"":""),"ptime="+encodeURIComponent(e.timings.DFPinit.timing||""),"dtime="+encodeURIComponent(c.DFPRendered?c.DFPRendered.timing:""),"stime="+encodeURIComponent(c.loaded?
c.loaded.timing:""),"ftime="+encodeURIComponent(c.viewable?c.viewable.timing:""),"moatftime="+encodeURIComponent(c.moatViewable?c.moatViewable.timing:""),"moat100ftime="+encodeURIComponent(c.moatFullViewable?c.moatFullViewable.timing:""),"zc="+encodeURIComponent(c.uuid||c.slot?c.slot.getTargeting("zc")||"":""),"zcp="+encodeURIComponent(e._UUID||""),"refresh="+encodeURIComponent(c.refresh||""),"err="+encodeURIComponent(c.errors?c.errors.join(","):""),"adtype="+encodeURIComponent(c.safeFrame?"safeFrame":
"fif"),"actview="+encodeURIComponent(c.activeViewEngine||"")];d=e.win.document.createElement("img");d.width=1;d.height=1;d.alt="zdvtools";d.style.position="absolute";d.src=a.join("&");e.debug("ZDVTools BBPIXEL: "+d.src,"blue");return!0},getName:function(a){try{var b=("string"===typeof a?a:a.id).match(/google_ads_iframe_(.+)/)[1];return b&&-1==b.indexOf("__hidden")?b:null}catch(d){return null}},getAd:function(a,b){if(!a)return null;var d=ZDVTools;"undefined"===typeof d.ads[a]&&(d.ads[a]=[]);var c=
d.ads[a]&&0<d.ads[a].length?d.ads[a].length-1:0;b&&d.ads[a]&&d.ads[a][c].DFPRendered&&(c+=1);if("undefined"===typeof d.ads[a][c]){var e={timestamp:(new Date).getTime(),timing:d.roundTiming(d.win.performance.now())};d.ads[a].push({name:a,iframeId:null,adUnitPath:null,init:e,loaded:null,viewable:null,moatViewable:null,moatFullViewable:null,creativeId:null,lineItemId:null,containerId:null,size:null,width:null,height:null,slot:null,uuid:null,safeFrame:!1,errors:[],refresh:c,DFPRendered:!1,slowAd:null,
isEmpty:!1,activeViewEngine:null});d.slowAdThreshold&&(d.ads[a][c].slowAd=d.win.setTimeout(function(){var b=d.ads[a][c];try{document.getElementById(b.iframeId).contentWindow.document.body.innerHTML||b.isEmpty?b.errors.push("SLOWAD"):b.errors.push("EMPTYAD")}catch(e){b.errors.push("SLOWAD")}b.slowAd=null},d.slowAdThreshold))}return d.ads[a][c]},_adLoaded:function(){if(!this||!this.src||"about:blank"!==this.src){var a=ZDVTools,b=a.getName(this);if(b){var d=a.getAd(b);if(!d.loaded){d.loaded={timestamp:(new Date).getTime(),
timing:a.roundTiming(a.win.performance.now())};try{document.getElementById(d.iframeId).contentWindow.document.body.innerHTML||d.errors.push("EMPTYAD")}catch(c){}a.trackZDBB("LOADED",this,b,d);if(d.slowAd)try{a.win.clearTimeout(d.slowAd),d.slowAd=null}catch(e){}for(b=0;b<a.onLoaded.length;b++)a.onLoaded[b](d);try{var a={},f;for(f in d)"slot"!=f&&(a[f]=d[f]);window.postMessage({agent:"zdvtool",event:"adLoaded",elementId:d.containerId,ad:a},"*")}catch(g){}}}else a.debug("ZDVTools sanity error on ad loaded "+
this.id)}},_adViewable:function(a,b,d,c,e){var f=ZDVTools;try{if(window.parent!=window&&window.parent.ZDVTools)return window.parent.ZDVTools.adViewable(a,b,d,c,e)}catch(g){}a||(a=this);b||(b=f.getName(a));if(b){d||(d=f.getAd(b));var h=d.loaded;e=e?"moatViewable":"viewable";if("undefined"===typeof d[e]||!d[e]||!d[e].timestamp){h&&h.timing?d[e]={timestamp:(new Date).getTime(),timing:Number(Math.round(f.roundTiming(f.win.performance.now())-h.timing+"e3")+"e-3")}:(f.debug("ZDVTools sanity error: ad viewable but not loaded "+
a.id),d[e]={timestamp:(new Date).getTime(),timing:-f.roundTiming(f.win.performance.now())});c&&(-1!=c.indexOf("id=osdim")?d.activeViewEngine="osdim":-1!=c.indexOf("id=lidar")&&(d.activeViewEngine="lidar"));f.trackZDBB(e.toUpperCase(),a,b,d);if(f.onViewable&&d.viewable)for(a=0;a<f.onViewable.length;a++)f.onViewable[a](d);try{var f={},k;for(k in d)"slot"!=k&&(f[k]=d[k]);window.postMessage({agent:"zdvtool",event:e.toUpperCase(),elementId:d.containerId,ad:f},"*")}catch(m){}}}else f.debug("ZDVTools sanity error on ad viewable: can't find iframe "+
a.id)},_MoatCallback:function(a){if(a.wasViewable&&window.frameElement)try{window.top.ZDVTools._adViewable(window.frameElement,null,null,"","moat")}catch(b){try{parent.postMessage({agent:"zdvtools",event:"MOATVIEWABLE",url:"moat",name:window.name,safeFrameUrl:window.location.href,safeFrameId:window.frameElement.id||""},"*")}catch(d){}}},_tick:function(){for(var a=ZDVTools,b=a.win.document.getElementsByTagName("iframe"),d=0;d<b.length;d++){var c=b[d],e=a.getName(c);if(e){var f=a.getAd(e),g=null;c._ZDVToolsOnLoad||
(c.addEventListener("load",a._adLoaded,!1),c._ZDVToolsOnLoad=!0);!f.containerId&&c.parentNode&&c.parentNode.parentNode&&(f.containerId=c.parentNode.parentNode.id||c.parentNode.id);f.iframeId||(f.iframeId=c.id);if(!f.safeFrame||a.enableSafeFramesHack){try{g=c.contentWindow?c.contentWindow:null}catch(h){if(!a.enableSafeFramesHack||-1!=c.name.indexOf(a.scriptUrl)||f.safeFrame){f.safeFrame=!0;continue}a._bootstrapSafeFrame(c)}try{g.yourMoatListener||(g.yourMoatListener=a._MoatCallback)}catch(k){}try{if(!f.viewable&&
g&&g.google_image_requests&&g.google_image_requests.length)for(var m=0;m<g.google_image_requests.length;m++){var l=g.google_image_requests[m].src;l&&-1==a._msgs.indexOf(l+" ")&&(-1!=l.indexOf("pagead2.googlesyndication.com/activeview?")&&a._adViewable(c,e,f,l),a._msgs+=l+" ")}}catch(n){}}}}},_bootstrapSafeFrame:function(a,b,d){if(a&&a.name&&a.src){a.id||(a.id="safeframe-"+Math.round(1E4*Math.random()));var c=ZDVTools;if(c.enableSafeFramesHack&&-1==a.name.indexOf(c.scriptUrl)){b=c.getName(a);d||(d=
c.getAd(b));var e=a.src;b='<script>window.safeFrameId="'+a.id+'";\x3c/script><script src="'+c.scriptUrl+'">\x3c/script>';a.src="about:blank";a.name=-1!=a.name.indexOf("/script>")?a.name.replace("\x3c/script>","\x3c/script>"+b):a.name.replace("</body>",b+"</body>");c.debug("ZDVTools: bootstrapping safeframe "+a.id);d.safeFrame||(d.safeFrame="rebooting",a.addEventListener("load",function(){if("about:blank"==this.src||"javascript:\"<html><body style='background:transparent'></body></html>"==this.src)this.contentWindow.name=
this.name,this.src=e,d.safeFrame="bootstrapped",c.debug("ZDVTools: bootstrapped frame "+a.id)}))}}},_tickInsideSafeFrame:function(){if("undefined"!==typeof google_image_requests&&google_image_requests.length){window._msgs||(window._msgs="");for(var a=0;a<google_image_requests.length;a++){var b=google_image_requests[a].src;if(b&&-1==window._msgs.indexOf(b+" ")){if(-1!=b.indexOf("pagead2.googlesyndication.com/activeview?")){try{parent.postMessage({agent:"zdvtoolsSafeFrame",event:"VIEWABLE",url:b,name:window.name,
safeFrameUrl:window.location.href,safeFrameId:window.safeFrameId||""},"*")}catch(d){}window._ZDVTickerInterval&&window.clearInterval(window._ZDVTickerInterval)}window._msgs+=b+" "}}}},receiveCrossFrameMessage:function(a){var b=a.data;if("string"==typeof b)try{b=JSON.parse(b)}catch(d){return}if(b.agent&&"zdvtoolsSafeFrame"==b.agent){var c=ZDVTools;if("SETSAFEFRAMEID"==b.event)b.safeFrameId&&(window.safeFrameId=b.safeFrameId);else{a=b.safeFrameId?document.getElementById(b.safeFrameId):null;if(!a||!c.getName(a)||
!a)if(b.name)try{a=document.getElementsByName(b.name)[0],c.getName(a)}catch(e){c.debug("Missing Safeframe in DOM");return}else if(b.safeFrameUrl)for(var f=document.getElementsByTagName("iframe"),g=0;g<f.length;g++){var h=f[g];if(h.src==b.safeFrameUrl){a=h;c.getName(a);break}}if("VIEWABLE"==b.event)c._adViewable(a,null,null,b.url);else if("MOATVIEWABLE"==b.event)c._adViewable(a,null,null,null,b.url);else if("SAFEFRAMEINIT"==b.event){b=c.getName(a);c=c.getAd(b);c.safeFrame||(c.safeFrame="native");try{a.contentWindow.postMessage({agent:"zdvtoolsSafeFrame",
event:"SETSAFEFRAMEID",url:window.location.href,name:a.name,safeFrameUrl:"",safeFrameId:a.id},"*")}catch(k){}}}}},initInsideSafeFrame:function(a,b){if(parent.postMessage){a.win.addEventListener("message",a.receiveCrossFrameMessage,!1);window._ZDVTickerInterval=window.setInterval(a._tickInsideSafeFrame,50);var d=a.getName(window.safeFrameId||window.name);try{parent.postMessage({agent:"zdvtoolsSafeFrame",event:"SAFEFRAMEINIT",url:"",name:d,safeFrameUrl:window.location.href,safeFrameId:window.safeFrameId||
""},"*")}catch(c){}}},initDFP:function(){var a=ZDVTools&&ZDVTools.win?ZDVTools.win:window;a.googletag=a.googletag||{};a.googletag.cmd=a.googletag.cmd||[];googletag.cmd.push(function(){var a=window.ZDVTools?window.ZDVTools:top.ZDVTools;a.timings.DFPinit={timestamp:(new Date).getTime(),timing:window.performance&&performance.now?a.roundTiming(performance.now()):null};googletag.pubads().addEventListener("slotRenderEnded",function(a){var b=window.ZDVTools||top.ZDVTools,e=b.getAd(a.slot.getSlotId().b);
e.adUnitPath=a.slot.getAdUnitPath();e.creativeId=a.creativeId;e.lineItemId=a.lineItemId;e.containerId=a.slot.getSlotId().f;e.correlatorId=googletag.pubads().getCorrelator();e.DFPRendered={timestamp:(new Date).getTime(),timing:b.roundTiming(b.win.performance.now())};try{e.size=a.size[0]+"x"+a.size[1],e.width=a.size[0],e.height=a.size[1]}catch(f){}if(a.isEmpty&&(e.isEmpty=!0,e.errors.push("DFPEMPTYAD"),e.slowAd))try{b.win.clearTimeout(e.slowAd),e.slowAd=null}catch(g){}e.slot=a.slot;e.uuid=a.slot.getTargeting("zc")||
null;a=googletag.pubads().j||{};a.zcp&&(zdv._UUID=a.zcp)});a=googletag.pubads();a.refresh_orig=a.refresh;a.refresh=function(a,b){var e=window.ZDVTools?window.ZDVTools:top.ZDVTools;a||(a=googletag.pubads().getSlots());for(var f=0;f<a.length;f++){var g=a[f].getSlotId().b;e.getAd(g,"addnew")}googletag.pubads().refresh_orig(a,b)}})},init:function(a,b){if(document.addEventListener&&window.performance){if(!window.performance.now){Date.now=Date.now||function(){return(new Date).getTime()};var d=performance.timing&&
performance.timing.navigationStart?performance.timing.navigationStart:Date.now();window.performance.now=function(){return Date.now()-d}}try{if(window.frameElement&&(window.yourMoatListener=a._MoatCallback),window.parent!=window&&window.parent.ZDVTools)return}catch(c){return a.initInsideSafeFrame(a,b)}a.self=a;a.win=b&&b.window?b.window:window;b&&b.onLoad&&a.onLoaded.push(b.onLoad);b&&b.onLoaded&&a.onLoaded.push(b.onLoaded);b&&b.onViewed&&a.onViewable.push(b.onViewed);b&&b.onViewable&&a.onViewable.push(b.onViewable);
a.enableDebug=b&&"undefined"!==typeof b.enableDebug?b.enableDebug:a.enableDebug;a.enableDebug=b&&"undefined"!==typeof b.debug?b.debug:a.enableDebug;a.slowAdThreshold=b&&"undefined"!==typeof b.slowAdThreshold?b.slowAdThreshold:a.slowAdThreshold;a.enableSafeFramesHack=b&&"undefined"!==typeof b.enableSafeFramesHack?b.enableSafeFramesHack:a.enableSafeFramesHack;b&&b.UUID&&(a._UUID=b.UUID);b&&b.gcp&&(a._UUID=b.gcp);b&&b.initTiming&&(a.timings.init=b.initTiming);a.win.yourMoatListener||(a.win.yourMoatListener=
a._MoatCallback);a.win.addEventListener("message",a.receiveCrossFrameMessage,!1);a.initDFP();a._tickerInterval=a.win.setInterval(a._tick,75);setTimeout(a.throttleDown,22E3);return a}}};ZDVTools.init(ZDVTools,"undefined"!==typeof window.ZDVOptions?window.ZDVOptions:null)};
